In [6]:
lst = [1,2,3]
lst

[1, 2, 3]

In [7]:
import numpy as np 
arr = np.array(lst)
arr

array([1, 2, 3])

In [8]:
matrice = [[1,2],[3,4],[5,6]]
np.array(matrice)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
#Identity matrix 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.random.rand(5)

array([0.14105515, 0.37678431, 0.61832117, 0.52297976, 0.08484186])

In [27]:
np.random.rand(2,3)

array([[0.9622028 , 0.23430081, 0.73007794],
       [0.06629881, 0.40637056, 0.62520254]])

In [35]:
np.random.randn(2,3)

array([[-0.78817158,  0.22049119, -0.14130379],
       [-1.28300298,  1.89423009, -1.68697672]])

In [46]:
np.random.randint(1,100,4)

array([50, 68, 33, 58])

In [40]:
arr = np.arange(25)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
random_arr = np.random.randint(0,100,10)
random_arr

array([44, 94, 97, 72, 46, 27, 91, 66,  7, 33])

In [56]:
random_arr.reshape(2,5)

array([[44, 94, 97, 72, 46],
       [27, 91, 66,  7, 33]])

In [57]:
random_arr.shape


(10,)

In [51]:
arr.min()

0

In [52]:
#no() here as shape is an attribute of the array 
arr.shape

(25,)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [59]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [62]:
arr.shape

(25,)

In [63]:
arr.dtype

dtype('int32')

In [76]:
lst = [1,2,'shahriar']

In [77]:
a = np.array(lst)

In [78]:
a.dtype

dtype('<U11')

In [79]:
#NP Array indexing and selection

In [80]:
import numpy as np 
arr = np.arange(0,11)


In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr[0]

0

In [83]:
arr[4]

4

In [85]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [86]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [91]:
arr[3:]
#start mentioned here is not included 

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
arr

array([12, 12, 12,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
arr[0:3] = 12
#end is not included 

In [94]:
arr

array([12, 12, 12,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
slice_of_arr = arr[0:6]

In [96]:
slice_of_arr

array([12, 12, 12,  3,  4,  5])

In [97]:
slice_of_arr[:] = 99

In [98]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [99]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [100]:
arr_copy_slice = slice_of_arr.copy()

In [101]:
arr_copy_slice

array([99, 99, 99, 99, 99, 99])

In [102]:
arr_copy_slice[:] = 12

In [103]:
arr_copy_slice

array([12, 12, 12, 12, 12, 12])

In [104]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [105]:
arr_2d = np.array([[1,2],[3,4],[5,6]])

In [107]:
arr_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [108]:
arr_2d[0]

array([1, 2])

In [109]:
arr_2d[1]

array([3, 4])

In [110]:
arr_2d[1,1]

4

In [112]:
arr_2d[2,1]

6

In [113]:
arr_2d[:2]

array([[1, 2],
       [3, 4]])

In [114]:
arr_2d[:2,1:]

array([[2],
       [4]])

In [115]:
arr2 = np.array([[5,10,15],[56,76,53],[43,34,423]])

In [116]:
arr2

array([[  5,  10,  15],
       [ 56,  76,  53],
       [ 43,  34, 423]])

In [117]:
arr2[0]

array([ 5, 10, 15])

In [120]:
arr2[2,1:]

array([ 34, 423])

In [121]:
arr = np.arange(1,11)

In [122]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [126]:
bool_arr = arr > 5

In [127]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [128]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [132]:
a = arr[arr<4]
print(a)

[1 2 3]


In [130]:
arr[arr>9]

array([10])

In [135]:
arr2 = np.arange(50).reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [139]:
arr2[1,3:6]

array([13, 14, 15])

In [140]:
#Numpy operations 

In [144]:
import numpy as np 
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [146]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [147]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [148]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [149]:
arr * 2 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [153]:
a = arr + arr - 2


In [154]:
a

array([-2,  0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [160]:
arr / 10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [169]:
a = arr**2 

In [170]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [171]:
#Universal array functions 

In [172]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [173]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [174]:
np.max(arr)

10

In [175]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])